# Generated by Django 5.2.6 on 2025-11-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appLiher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='devoluciones',
        ),
    ]
