# Generated by Django 5.2.6 on 2025-11-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLiher', '0002_remove_permiso_devoluciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='devoluciones',
            field=models.BooleanField(default=False),
        ),
    ]
